/*.
 * This Spock specification was generated by the Gradle 'init' task.
 */
package inventory

import spock.lang.Specification
import spock.lang.Unroll
import java.io.InputStream


class AppSpec extends Specification {
}

