/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package inventory

import spock.lang.Specification
import spock.lang.Unroll

class AppTest extends Specification {


	@Unroll
	def "We add some new Items in the List and we excpect the list not empty "(){
		given:
		ArrayList<Item> items = new ArrayList<>()
		Item item1 = new Item("Xbox One", "AXB124AXY",BigInteger.valueOf(399))
		Item item2 = new Item("Samsung TV", "S40AZBDE4", BigInteger.valueOf(599))
		items.add(item1)
		items.add(item2)

		expect:
		items.size() != 0
	}
}
