/*
 * This Java souitemsrce file was generated by the Gradle 'init' task.
 */
package inventory;

import java.util.ArrayList;
import java.util.Scanner;



public class App {
	static Scanner scanner = new Scanner(System.in);
	static ArrayList<Item> items = new ArrayList<>();

	public static void main(String[] args) {

		addingItemsFromUserInput();

	}
	
	private static void addingItemsFromUserInput() {
		boolean addingItem = true;
		while (addingItem) {
			System.out.println("Please enter the item info NAME,Serial Number,Value respectively ");
			items.add(new Item(scanner.nextLine(), scanner.nextLine(), scanner.nextBigDecimal()));
			System.out.println("Item has been added");
			System.out.println("do you want to add new item? : Y,N");
			if (scanner.next().charAt(0) == 'N') {
				addingItem = false;
			}
		}
		scanner.close();
	}

}