/*
 * This Java souitemsrce file was generated by the Gradle 'init' task.
 */
package inventory;

public class App {

	public static void main(String[] args) {
		Menu.addingItemsFromUserInput();
	}

}
